Repository MIDNEAR/MIDNEAR_BACKEND, pull requests merged in 2025-01, with the labels that each got.

#6 [Feat] inquiry#2
  .gitignore
  build.gradle
  src/main/java/com/midnear/midnearshopping/config/.gitkeep
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/.gitkeep
  src/main/java/com/midnear/midnearshopping/controller/InquirieController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/.gitkeep
  src/main/java/com/midnear/midnearshopping/domain/dto/Inquiries/InquiriesDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/Inquiries/Inquiry_commentsDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/InquiriesDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/Inquiry_commentsDTO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/.gitkeep
  src/main/java/com/midnear/midnearshopping/domain/vo/Inquiries/InquiriesVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/Inquiries/Inquiry_commentsVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/InquiriesVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/Inquiry_commentsVO.java
  src/main/java/com/midnear/midnearshopping/mapper/.gitkeep
  src/main/java/com/midnear/midnearshopping/mapper/InquiriesMapper.java
  src/main/java/com/midnear/midnearshopping/service/.gitkeep
  src/main/java/com/midnear/midnearshopping/service/InquirieService.java
  src/main/java/com/midnear/midnearshopping/service/InquirieServiceImpl.java
  src/main/resources/mapper/.gitkeep
  src/main/resources/mapper/InquiriesMapper.xml
  src/main/resources/project.sql
Labels: ✨ Feature

#8 [Feat] admin notice#4
  src/main/java/com/midnear/midnearshopping/controller/NoticeController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/notice/NoticeDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/NoticeVo.java
  src/main/java/com/midnear/midnearshopping/mapper/notice/NoticeMapper.java
  src/main/java/com/midnear/midnearshopping/service/NoticeService.java
  src/main/resources/mapper/NoticeMapper.xml
Labels: ✨ Feature

#9 [Feat] inquiry list#7
  src/main/java/com/midnear/midnearshopping/controller/InquirieController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/Inquiries/InquiriesListDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/Inquiry_commentsDTO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/InquiriesVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/Inquiry_commentsVO.java
  src/main/java/com/midnear/midnearshopping/mapper/Inquiries/InquiriesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/InquiriesMapper.java
  src/main/java/com/midnear/midnearshopping/service/InquirieService.java
  src/main/java/com/midnear/midnearshopping/service/InquirieServiceImpl.java
  src/main/resources/mapper/InquiriesMapper.xml
Labels: ✨ Feature

#12 [Feat] 전화번호 인증 구현#3
  build.gradle
  src/main/java/com/midnear/midnearshopping/config/RedisConfig.java
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/config/SmsCertificationUtil.java
  src/main/java/com/midnear/midnearshopping/controller/SmsController.java
  src/main/java/com/midnear/midnearshopping/controller/UsersController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/users/LoginDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/users/SmsRequestDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/users/SmsVerifyDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/users/UsersDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/users/CustomUserDetails.java
  src/main/java/com/midnear/midnearshopping/domain/vo/users/CustomUserDetailsService.java
  src/main/java/com/midnear/midnearshopping/domain/vo/users/SmsRepository.java
  src/main/java/com/midnear/midnearshopping/domain/vo/users/UsersVO.java
  src/main/java/com/midnear/midnearshopping/jwt/JwtUtil.java
  src/main/java/com/midnear/midnearshopping/mapper/users/UsersMapper.java
  src/main/java/com/midnear/midnearshopping/service/SmsService.java
  src/main/java/com/midnear/midnearshopping/service/UsersService.java
  src/main/resources/mapper/UsersMapper.xml
Labels: ✨ Feature

#13 [Feat] 이미지 업로드, 삭제
  build.gradle
  src/main/java/com/midnear/midnearshopping/config/S3Config.java
  src/main/java/com/midnear/midnearshopping/controller/NoticeController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/FileDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/notice/NoticeDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/notice/NoticeImagesDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/notice/NoticeImagesVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/notice/NoticeVo.java
  src/main/java/com/midnear/midnearshopping/mapper/notice/NoticeImagesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/notice/NoticeMapper.java
  src/main/java/com/midnear/midnearshopping/service/NoticeService.java
  src/main/java/com/midnear/midnearshopping/service/S3Service.java
  src/main/resources/mapper/NoticeImagesMapper.xml
  src/main/resources/mapper/NoticeMapper.xml
Labels: ✨ Feature

#18 [Feat] 소셜로그인 구현
  build.gradle
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/OAuth2Controller.java
  src/main/java/com/midnear/midnearshopping/controller/UsersController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/users/SocialUserInfoDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/users/UsersDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/users/UsersVO.java
  src/main/java/com/midnear/midnearshopping/mapper/users/UsersMapper.java
  src/main/java/com/midnear/midnearshopping/service/oauth/OAuthGoogleProvider.java
  src/main/java/com/midnear/midnearshopping/service/oauth/OAuthKaKaoProvider.java
  src/main/java/com/midnear/midnearshopping/service/oauth/OAuthNaverProvider.java
  src/main/java/com/midnear/midnearshopping/service/oauth/OAuthProvider.java
  src/main/java/com/midnear/midnearshopping/service/oauth/OAuthService.java
  src/main/resources/mapper/UsersMapper.xml
  src/main/resources/project.sql
Labels: ✨ Feature

#22 [Fix] 인가코드 백엔드에서 디코딩하도록 변경.
  src/main/java/com/midnear/midnearshopping/controller/OAuth2Controller.java
Labels: 🔨 Refactor

#27 [Feat] 상품 관련 dto, vo
  src/main/java/com/midnear/midnearshopping/controller/NoticeController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/notice/NoticeDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/notice/NoticeImagesDto.java
  src/main/java/com/midnear/midnearshopping/domain/products/ProductColorsDto.java
  src/main/java/com/midnear/midnearshopping/domain/products/ProductsDto.java
  src/main/java/com/midnear/midnearshopping/domain/products/SizesDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/notice/NoticeImagesVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/notice/NoticeVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/products/ProductColorsVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/products/ProductsVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/products/SizesVo.java
  src/main/java/com/midnear/midnearshopping/mapper/notice/NoticeImagesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/notice/NoticeMapper.java
  src/main/java/com/midnear/midnearshopping/service/NoticeService.java
  src/main/resources/mapper/NoticeImagesMapper.xml
Labels: ✨ Feature

#28 [Feat] order search#24
  .github/Pipeline Script
  src/main/java/com/midnear/midnearshopping/controller/DisruptiveController.java
  src/main/java/com/midnear/midnearshopping/controller/InquirieController.java
  src/main/java/com/midnear/midnearshopping/controller/MagazinesController.java
  src/main/java/com/midnear/midnearshopping/controller/OrderController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/OrderDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/OrderParamDTO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/order/OrderProductsVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/order/OrdersVO.java
  src/main/java/com/midnear/midnearshopping/mapper/magazines/magazinesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/order/OrderProductsMapper.java
  src/main/java/com/midnear/midnearshopping/service/disruptive/DisruptiveService.java
  src/main/java/com/midnear/midnearshopping/service/disruptive/DisruptiveServiceImpl.java
  src/main/java/com/midnear/midnearshopping/service/inquirie/InquirieService.java
  src/main/java/com/midnear/midnearshopping/service/inquirie/InquirieServiceImpl.java
  src/main/java/com/midnear/midnearshopping/service/magazine/MagazinesService.java
  src/main/java/com/midnear/midnearshopping/service/magazine/MagazinesServiceImpl.java
  src/main/java/com/midnear/midnearshopping/service/order/OrderProductService.java
  src/main/java/com/midnear/midnearshopping/service/order/OrderProductServiceImpl.java
  src/main/resources/mapper/OrderProductMapper.xml
  src/main/resources/project.sql
Labels: ✨ Feature

#31 [Fix] 유저 정보 및 아이디찾기 오류 수정
  src/main/java/com/midnear/midnearshopping/service/UsersService.java
Labels: 🐞 BugFix

#36 [Feat] 상품 관리
  src/main/java/com/midnear/midnearshopping/controller/ProductManagementController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/category/CategoryDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductColorsDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductColorsListDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductManagementListDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductsDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/SizesDto.java
  src/main/java/com/midnear/midnearshopping/domain/enums/ProductStatus.java
  src/main/java/com/midnear/midnearshopping/domain/products/ProductColorsDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/category/CategoryVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/products/ProductColorsVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/products/ProductImagesVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/products/ProductsVo.java
  src/main/java/com/midnear/midnearshopping/mapper/Category/CategoriesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductColorsMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductImagesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductsMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/products/SizesMapper.java
  src/main/java/com/midnear/midnearshopping/service/ProductManagementService.java
  src/main/resources/mapper/CategoriesMapper.xml
  src/main/resources/mapper/ProductColorsMapper.xml
  src/main/resources/mapper/ProductImagesMapper.xml
  src/main/resources/mapper/ProductsMapper.xml
  src/main/resources/mapper/SizesMapper.xml
Labels: ✨ Feature

#37 [Feat] 배송지 생성, 조회, 전체조회 수정 삭제
  src/main/java/com/midnear/midnearshopping/controller/DeliveryController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/delivery/DeliveryAddrDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/delivery/UpdateDeliveryRequest.java
  src/main/java/com/midnear/midnearshopping/domain/vo/delivery/DeliveryAddressVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/delivery/DeliveryInfoVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/users/UsersVO.java
  src/main/java/com/midnear/midnearshopping/mapper/delivery/DeliveryAddressMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/users/UsersMapper.java
  src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
  src/main/resources/mapper/DeliveryAddressMapper.xml
  src/main/resources/mapper/OrderProductMapper.xml
  src/main/resources/mapper/UsersMapper.xml
Labels: ✨ Feature

#40 [Feat] 상품 목록 조회, 상세 조회
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/ProductController.java
  src/main/java/com/midnear/midnearshopping/controller/ProductManagementController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductDetailColorDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductDetailSizeDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductsDetailDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductsListDto.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductColorsMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductImagesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductsMapper.java
  src/main/java/com/midnear/midnearshopping/service/product/ProductService.java
  src/main/resources/mapper/ProductColorsMapper.xml
  src/main/resources/mapper/ProductImagesMapper.xml
  src/main/resources/mapper/ProductsMapper.xml
Labels: ✨ Feature

#41 [Feat] 취소관리
  build.gradle
  src/main/java/com/midnear/midnearshopping/controller/CancelProductController.java
  src/main/java/com/midnear/midnearshopping/controller/ConfirmPurchaseController.java
  src/main/java/com/midnear/midnearshopping/controller/OrderShippingController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/CancelProductDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OptionQuantityDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OrderReciptDTO.java
  src/main/java/com/midnear/midnearshopping/mapper/productManagement/CancelProductMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/productManagement/OrderShippingMapper.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/CancelProductService.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/CancelProductServiceImpl.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/OrderShippingService.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/OrderShippingServiceImpl.java
  src/main/resources/mapper/CancelProductMapper.xml
  src/main/resources/mapper/OrderShippingMapper.xml
Labels: ✨ Feature

#45 [Feat] 교환관리
  src/main/java/com/midnear/midnearshopping/controller/ExchangeController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ExchangeDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ExchangeParamDTO.java
  src/main/java/com/midnear/midnearshopping/mapper/productManagement/ExchangeMapper.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/ExchangeService.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/ExchangeServiceImpl.java
  src/main/resources/mapper/CancelProductMapper.xml
  src/main/resources/mapper/ExchangeMapper.xml
Labels: ✨ Feature

#46 [Feat] 반품상품 관리
  src/main/java/com/midnear/midnearshopping/controller/productManage/CancelProductController.java
  src/main/java/com/midnear/midnearshopping/controller/productManage/ConfirmPurchaseController.java
  src/main/java/com/midnear/midnearshopping/controller/productManage/ExchangeController.java
  src/main/java/com/midnear/midnearshopping/controller/productManage/OrderController.java
  src/main/java/com/midnear/midnearshopping/controller/productManage/OrderShippingController.java
  src/main/java/com/midnear/midnearshopping/controller/productManage/ReturnController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ReturnDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ReturnParamDTO.java
  src/main/java/com/midnear/midnearshopping/mapper/productManagement/ReturnMapper.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/ReturnService.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/ReturnServiceImpl.java
  src/main/resources/mapper/ReturnMapper.xml
Labels: ✨ Feature

#48 [Feat] 상품 수정, 검색 필터링
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/ProductManagementController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/category/CategoryDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductColorsDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductColorsListDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductManagementListDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductsDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/SizesDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/shipping_returns/ShippingReturnsDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/products/ProductColorsVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/products/ProductsVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/products/SizesVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/shipping_returns/ShippingReturnsVo.java
  src/main/java/com/midnear/midnearshopping/mapper/Category/CategoriesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/ShippingReturns/ShippingReturnsMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductColorsMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductImagesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductsMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/products/SizesMapper.java
  src/main/java/com/midnear/midnearshopping/service/ProductManagementService.java
  src/main/resources/mapper/CategoriesMapper.xml
  src/main/resources/mapper/ProductColorsMapper.xml
  src/main/resources/mapper/ProductImagesMapper.xml
  src/main/resources/mapper/ProductsMapper.xml
  src/main/resources/mapper/ShippingReturnsMapper.xml
  src/main/resources/mapper/SizesMapper.xml
Labels: ✨ Feature

#49 [Feat] 공지사항 검색 및 필터링 추가
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/NoticeController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/notice/NoticeDto.java
  src/main/java/com/midnear/midnearshopping/mapper/notice/NoticeImagesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/notice/NoticeMapper.java
  src/main/java/com/midnear/midnearshopping/service/NoticeService.java
  src/main/resources/mapper/NoticeMapper.xml
  src/main/resources/mapper/ProductColorsMapper.xml
Labels: ✨ Feature

#53 [Feat] 스토어 관리
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/StoreManagementController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/category/CreateCategoryDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/policies_info/PoliciesAndInfoDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/storeImages/StoreImagesDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/policies_info/PoliciesAndInfoVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/storeImages/StoreImagesVo.java
  src/main/java/com/midnear/midnearshopping/mapper/Category/CategoriesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/policies_info/PoliciesAndInfoMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/storeManagement/StoreImagesMapper.java
  src/main/java/com/midnear/midnearshopping/service/StoreManagementService.java
  src/main/resources/mapper/CategoriesMapper.xml
  src/main/resources/mapper/PoliciesAndInfoMapper.xml
  src/main/resources/mapper/StoreImagesMapper.xml
Labels: ✨ Feature

#54 [Feat]주문내역 조회, 주문 생성 리팩토링#38
  src/main/java/com/midnear/midnearshopping/controller/UserOrderController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/OrderDetailsDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/OrderProductsRequestDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/UserOrderCheckDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/UserOrderDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/UserOrderProductCheckDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/UserOrderProductsDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/order/OrderProductsVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/order/OrdersVO.java
  src/main/java/com/midnear/midnearshopping/mapper/order/OrderMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/order/UserOrderProductsMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/products/SizesMapper.java
  src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
  src/main/resources/mapper/OrderMapper.xml
  src/main/resources/mapper/SizesMapper.xml
  src/main/resources/mapper/UserOrderProductsMapper.xml
Labels: ✨ Feature, 🔨 Refactor

#55 [Feat] 교환, 환불, 취소 요청, 문의, 비회원 주문, 리뷰 작성#38
  src/main/java/com/midnear/midnearshopping/controller/ClaimController.java
  src/main/java/com/midnear/midnearshopping/controller/DeliveryController.java
  src/main/java/com/midnear/midnearshopping/controller/ReviewController.java
  src/main/java/com/midnear/midnearshopping/controller/UserInquiryController.java
  src/main/java/com/midnear/midnearshopping/controller/UserOrderController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/Inquiries/InquiryRequestDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/claim/CancelRequestDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/claim/ExchangeRequestDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/claim/ReturnRequestDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/NonUserOrderDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/OrderDetailsDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/OrderProductDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/review/ReviewRequestDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/Inquiries/InquiriesVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/claim/CanceledProductVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/claim/ExchangeVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/claim/ReturnsVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/review/ReviewImagesVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/review/ReviewsVO.java
  src/main/java/com/midnear/midnearshopping/mapper/Inquiries/UserInquiryMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/cart/CartMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/claim/UserCanceledProductMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/claim/UserExchangeMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/claim/UserReturnsMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/order/UserOrderProductsMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/review/ReviewImagesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/review/ReviewsMapper.java
  src/main/java/com/midnear/midnearshopping/service/cart/CartService.java
  src/main/java/com/midnear/midnearshopping/service/claim/ClaimService.java
  src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
  src/main/java/com/midnear/midnearshopping/service/inquirie/UserInquiryService.java
  src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
  src/main/java/com/midnear/midnearshopping/service/review/ReviewsService.java
  src/main/resources/mapper/ReviewImagesMapper.xml
  src/main/resources/mapper/ReviewsMapper.xml
  src/main/resources/mapper/UserCanceledProductMapper.xml
  src/main/resources/mapper/UserExchangeMapper.xml
  src/main/resources/mapper/UserInquiryMapper.xml
  src/main/resources/mapper/UserOrderProductsMapper.xml
  src/main/resources/mapper/UserReturnsMapper.xml
Labels: ✨ Feature

#57 [Feat] 통계
  src/main/java/com/midnear/midnearshopping/controller/StoreManagementController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/Statistics/StatisticsDto.java
  src/main/java/com/midnear/midnearshopping/mapper/Category/CategoriesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/storeManagement/StatisticsMapper.java
  src/main/java/com/midnear/midnearshopping/service/StoreManagementService.java
  src/main/resources/mapper/CategoriesMapper.xml
  src/main/resources/mapper/StatisticsMapper.xml
Labels: ✨ Feature

#60 [Feat] 쿠폰/포인트 지급 관리
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/CouponPointController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/coupon_point/CouponDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/coupon_point/CouponToSelectedUserDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/coupon_point/PointDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/coupon_point/PointToSelectedUserDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/coupon_point/CouponVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/coupon_point/PointVo.java
  src/main/java/com/midnear/midnearshopping/domain/vo/coupon_point/ReviewPointVo.java
  src/main/java/com/midnear/midnearshopping/mapper/coupon_point/CouponMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/coupon_point/PointMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/users/UsersMapper.java
  src/main/java/com/midnear/midnearshopping/service/CouponPointService.java
  src/main/resources/mapper/CouponMapper.xml
  src/main/resources/mapper/PointMapper.xml
  src/main/resources/mapper/UsersMapper.xml
Labels: ✨ Feature

#62 [Feat]etc#58
  build.gradle
  src/main/java/com/midnear/midnearshopping/MidnearShoppingApplication.java
  src/main/java/com/midnear/midnearshopping/config/AppConfig.java
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/InquirieController.java
  src/main/java/com/midnear/midnearshopping/controller/MagazinesController.java
  src/main/java/com/midnear/midnearshopping/controller/productManage/OrderShippingController.java
  src/main/java/com/midnear/midnearshopping/controller/productManage/ShippingManageController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/delivery/DeliveryInfoDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ConfirmPurchaseDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/InvoiceInsertDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OptionQuantityDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OrderDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OrderReciptDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OrderShippingDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ShippingManageDTO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/delivery/DeliveryInfoVO.java
  src/main/java/com/midnear/midnearshopping/mapper/Inquiries/InquiriesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/productManagement/OrderShippingMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/productManagement/ShippingManagementMapper.java
  src/main/java/com/midnear/midnearshopping/service/inquirie/InquirieService.java
  src/main/java/com/midnear/midnearshopping/service/inquirie/InquirieServiceImpl.java
  src/main/java/com/midnear/midnearshopping/service/magazine/MagazinesServiceImpl.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/DeliveryService.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/DeliveryServiceImpl.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/OrderShippingService.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/OrderShippingServiceImpl.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/ReturnService.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/ShippingManageService.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/ShippingManageServiceImpl.java
  src/main/resources/mapper/ConfirmPurchaseMapper.xml
  src/main/resources/mapper/InquiriesMapper.xml
  src/main/resources/mapper/OrderProductMapper.xml
  src/main/resources/mapper/OrderShippingMapper.xml
  src/main/resources/mapper/ReturnMapper.xml
  src/main/resources/mapper/ShippingManagement.xml
Labels: ✨ Feature
