Repository MIDNEAR/MIDNEAR_BACKEND, pull requests merged in 2025-02, with the labels that each got.

#64 [Feat] 비회원 주문조회 매거진 조회 #38
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/UserMagazineController.java
  src/main/java/com/midnear/midnearshopping/controller/UserOrderController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/magazines/MagazineResponseDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/magazines/MagazineResponseListDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/NonUserOrderDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/NonUserOrderInfoRequest.java
  src/main/java/com/midnear/midnearshopping/domain/vo/order/OrdersVO.java
  src/main/java/com/midnear/midnearshopping/mapper/magazines/magazinesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/order/OrderMapper.java
  src/main/java/com/midnear/midnearshopping/service/magazine/UserMagazineService.java
  src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
  src/main/resources/mapper/MagazinesMapper.xml
  src/main/resources/mapper/OrderMapper.xml
  src/main/resources/mapper/UserCanceledProductMapper.xml
Labels: ✨ Feature

#65 [Feat] 코디상품 필터링 검색 범위 추가
  src/main/java/com/midnear/midnearshopping/controller/ProductManagementController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductColorsDto.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductsMapper.java
  src/main/java/com/midnear/midnearshopping/service/ProductManagementService.java
  src/main/resources/mapper/ProductColorsMapper.xml
  src/main/resources/mapper/ProductsMapper.xml
Labels: ✨ Feature, 🔨 Refactor

#68 [Feat]포인트 추가, 교환시 픽업테이블 생성#38
  src/main/java/com/midnear/midnearshopping/domain/dto/claim/ExchangePickupDeliveryDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/review/ReviewListDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/review/ReviewsVO.java
  src/main/java/com/midnear/midnearshopping/mapper/claim/UserExchangeMapper.java
  src/main/java/com/midnear/midnearshopping/service/claim/ClaimService.java
  src/main/resources/mapper/ReviewsMapper.xml
  src/main/resources/mapper/UserCanceledProductMapper.xml
  src/main/resources/mapper/UserExchangeMapper.xml
Labels: ✨ Feature

#70 [Chore] 자잘한 수정
  src/main/java/com/midnear/midnearshopping/controller/productManage/CancelProductController.java
  src/main/java/com/midnear/midnearshopping/controller/productManage/OrderShippingController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ConfirmPurchaseDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ExchangeDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/ExchangeParamDTO.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OptionQuantityDTO.java
  src/main/resources/mapper/ExchangeMapper.xml
  src/main/resources/mapper/OrderShippingMapper.xml
Labels: 🐞 BugFix

#71 [Fix] Cors,매거진 픽스#38
  src/main/java/com/midnear/midnearshopping/config/CorsConfig.java
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/DeliveryController.java
  src/main/java/com/midnear/midnearshopping/controller/UserMagazineController.java
  src/main/java/com/midnear/midnearshopping/controller/UserOrderController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/magazines/MagazineResponseDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/OrderDetailsDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/order/UserOrderProductCheckDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/payment/PaymentInfoDto.java
  src/main/java/com/midnear/midnearshopping/mapper/delivery/DeliveryInfoMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/magazines/magazinesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/order/OrderMapper.java
  src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
  src/main/java/com/midnear/midnearshopping/service/magazine/UserMagazineService.java
  src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
  src/main/resources/mapper/DeliveryInfoMapper.xml
  src/main/resources/mapper/MagazinesMapper.xml
  src/main/resources/mapper/OrderMapper.xml
  src/main/resources/mapper/ReviewsMapper.xml
Labels: 🐞 BugFix

#72 [Feat] 리뷰 포인트 적립
  src/main/java/com/midnear/midnearshopping/controller/CouponPointController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/coupon_point/PointDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/coupon_point/PointVo.java
  src/main/java/com/midnear/midnearshopping/mapper/coupon_point/PointMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/coupon_point/ReviewPointMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/review/ReviewImagesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/review/ReviewsMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/users/UsersMapper.java
  src/main/java/com/midnear/midnearshopping/service/CouponPointService.java
  src/main/resources/mapper/PointMapper.xml
  src/main/resources/mapper/ReviewImagesMapper.xml
  src/main/resources/mapper/ReviewPointMapper.xml
  src/main/resources/mapper/ReviewsMapper.xml
  src/main/resources/mapper/UsersMapper.xml
Labels: ✨ Feature

#74 [Fix] 페이징 사이즈 수정
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/NoticeManagementController.java
  src/main/java/com/midnear/midnearshopping/service/notice/NoticeManagementService.java
Labels: 🔨 Refactor

#75 [Feat] 메인 화면 팝업 이미지
  src/main/java/com/midnear/midnearshopping/controller/NoticeController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/notice/PopupDto.java
  src/main/java/com/midnear/midnearshopping/mapper/notice/NoticeImagesMapper.java
  src/main/java/com/midnear/midnearshopping/service/notice/NoticeService.java
  src/main/resources/mapper/NoticeImagesMapper.xml
Labels: ✨ Feature

#76 [Fix] 유저쪽 버그 픽스, 리팩토링#73
  src/main/java/com/midnear/midnearshopping/config/CorsConfig.java
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/ReviewController.java
  src/main/java/com/midnear/midnearshopping/controller/UserCouponPointController.java
  src/main/java/com/midnear/midnearshopping/controller/UserMagazineController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/coupon_point/UserPointDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/review/CommentDto.java
  src/main/java/com/midnear/midnearshopping/mapper/magazines/magazinesMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/review/ReviewsMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/users/UsersMapper.java
  src/main/java/com/midnear/midnearshopping/service/CouponPointService.java
  src/main/java/com/midnear/midnearshopping/service/magazine/UserMagazineService.java
  src/main/java/com/midnear/midnearshopping/service/review/ReviewsService.java
  src/main/resources/mapper/MagazinesMapper.xml
  src/main/resources/mapper/PointMapper.xml
  src/main/resources/mapper/UserCouponMapper.xml
Labels: 🐞 BugFix, 🔨 Refactor

#77 [Fix] userbugfix#73
  src/main/java/com/midnear/midnearshopping/config/CorsConfig.java
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/UserOrderController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/payment/PaymentInfoDto.java
  src/main/java/com/midnear/midnearshopping/mapper/delivery/DeliveryAddressMapper.java
  src/main/java/com/midnear/midnearshopping/service/order/OrderNumberGenerator.java
  src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
  src/main/java/com/midnear/midnearshopping/service/order/PostalCodeChecker.java
  src/main/resources/mapper/DeliveryAddressMapper.xml
  src/main/resources/mapper/OrderMapper.xml
  src/main/resources/mapper/UsersMapper.xml
Labels: 🐞 BugFix

#78 [Refactor] 장바구니, 교환취소환불 리팩토링#73
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/ProductController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/CoordinateProductDto.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductsMapper.java
  src/main/java/com/midnear/midnearshopping/service/claim/ClaimService.java
  src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
  src/main/java/com/midnear/midnearshopping/service/product/ProductService.java
  src/main/resources/mapper/CartProductsMapper.xml
  src/main/resources/mapper/ProductsMapper.xml
  src/main/resources/mapper/UserOrderProductsMapper.xml
Labels: 🔨 Refactor

#79 [Refactor] Oauth Refactor#73
  src/main/java/com/midnear/midnearshopping/domain/dto/delivery/DeliveryAddrDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/review/ReviewRequestDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/users/UsersDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/cart/CartVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/coupon_point/UserCouponVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/delivery/DeliveryAddressVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/order/OrdersVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/review/ReviewsVO.java
  src/main/java/com/midnear/midnearshopping/domain/vo/users/UsersVO.java
  src/main/java/com/midnear/midnearshopping/mapper/cart/CartMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/coupon_point/PointMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/coupon_point/UserCouponMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/delivery/DeliveryAddressMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/order/OrderMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/users/UsersMapper.java
  src/main/java/com/midnear/midnearshopping/service/CouponPointService.java
  src/main/java/com/midnear/midnearshopping/service/cart/CartService.java
  src/main/java/com/midnear/midnearshopping/service/claim/ClaimService.java
  src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
  src/main/java/com/midnear/midnearshopping/service/inquirie/UserInquiryService.java
  src/main/java/com/midnear/midnearshopping/service/oauth/OAuthService.java
  src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
  src/main/java/com/midnear/midnearshopping/service/review/ReviewsService.java
Labels: ✨ Feature

#80 [Feat] FE요청: 전체상품 수와 페이지크기 리턴#73
  src/main/java/com/midnear/midnearshopping/controller/ProductController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductListInfoDto.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductsMapper.java
  src/main/java/com/midnear/midnearshopping/service/product/ProductService.java
  src/main/resources/mapper/ProductsMapper.xml
Labels: ✨ Feature

#81 [Fix] 매출 타입 수정
  src/main/java/com/midnear/midnearshopping/controller/StoreManagementController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/Statistics/StatisticsDto.java
  src/main/java/com/midnear/midnearshopping/mapper/storeManagement/StatisticsMapper.java
  src/main/java/com/midnear/midnearshopping/service/StoreManagementService.java
  src/main/resources/mapper/StatisticsMapper.xml
Labels: 🔨 Refactor

#82 [Fix] 상품 등록 시 날짜 오류 수정
  src/main/java/com/midnear/midnearshopping/controller/CouponPointController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductsDto.java
  src/main/java/com/midnear/midnearshopping/domain/vo/products/ProductsVo.java
Labels: 🐞 BugFix

#83 [Fix] Cors에 프엔 배포 추가
  src/main/java/com/midnear/midnearshopping/config/CorsConfig.java
Labels: 🔨 Refactor

#84 [Fix] Cors에 프엔 배포 추가 수정:
  src/main/java/com/midnear/midnearshopping/config/CorsConfig.java
Labels: 🐞 BugFix

#85 [Feat] fe요청 처리#73
  src/main/java/com/midnear/midnearshopping/controller/ProductController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductListInfoDto.java
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductsMapper.java
  src/main/java/com/midnear/midnearshopping/service/product/ProductService.java
  src/main/resources/mapper/ProductsMapper.xml
Labels: ✨ Feature

#87 [Fix]Error parsing HTTP request header해결 #73
  src/main/java/com/midnear/midnearshopping/controller/SmsController.java
Labels: 🐞 BugFix

#88 [Fix]페이징 바보짓 해결 #73
  src/main/java/com/midnear/midnearshopping/service/product/ProductService.java
Labels: ✨ Feature

#89 [Fix] 메인, 로고 이미지 업로드 시 nullPoint 에러, 이용약관 리팩토링
  src/main/java/com/midnear/midnearshopping/controller/StoreManagementController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/policies_info/PoliciesAndInfoDto.java
  src/main/java/com/midnear/midnearshopping/mapper/policies_info/PoliciesAndInfoMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/storeManagement/StoreImagesMapper.java
  src/main/java/com/midnear/midnearshopping/service/StoreManagementService.java
  src/main/resources/mapper/PoliciesAndInfoMapper.xml
  src/main/resources/mapper/StoreImagesMapper.xml
Labels: 🐞 BugFix

#91 [Fix] shipping&returns 리팩토링
  src/main/java/com/midnear/midnearshopping/mapper/ShippingReturns/ShippingReturnsMapper.java
  src/main/java/com/midnear/midnearshopping/service/ProductManagementService.java
  src/main/resources/mapper/ShippingReturnsMapper.xml
Labels: 🐞 BugFix

#92 [Fix] 코디 상품 dto 수정
  src/main/java/com/midnear/midnearshopping/domain/dto/coordinate/ColorDto.java
  src/main/java/com/midnear/midnearshopping/domain/dto/coordinate/MainProductDto.java
  src/main/java/com/midnear/midnearshopping/service/ProductManagementService.java
Labels: 🐞 BugFix

#93 [Feat]무료배송인지 조회#73
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/UserOrderController.java
  src/main/java/com/midnear/midnearshopping/mapper/order/OrderMapper.java
  src/main/java/com/midnear/midnearshopping/service/order/OrderService.java
  src/main/resources/mapper/OrderMapper.xml
Labels: ✨ Feature

#94 [Feat] footer 수정
  src/main/java/com/midnear/midnearshopping/controller/FooterController.java
  src/main/java/com/midnear/midnearshopping/controller/productManage/OrderShippingController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/productManagement/OrderShippingDTO.java
  src/main/java/com/midnear/midnearshopping/mapper/productManagement/OrderShippingMapper.java
  src/main/java/com/midnear/midnearshopping/mapper/storeManagement/FooterMapper.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/FooterService.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/FooterServiceImpl.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/OrderShippingService.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/OrderShippingServiceImpl.java
  src/main/resources/mapper/FooterMapper.xml
  src/main/resources/mapper/OrderShippingMapper.xml
Labels: ✨ Feature

#95 [Feat]상품리스트에 판매상태, 할인기간 포함/이미지 제대로 나오게 수정
  src/main/java/com/midnear/midnearshopping/domain/dto/products/ProductsListDto.java
  src/main/resources/mapper/ProductsMapper.xml
Labels: ✨ Feature

#96 [Fix] 상품 등록 시 할인 기간 null 가능
  src/main/java/com/midnear/midnearshopping/domain/vo/products/ProductsVo.java
Labels: 🐞 BugFix

#97 [Feat] FE요청: 페이지 사이즈 4로 수정 #73
  src/main/java/com/midnear/midnearshopping/service/product/ProductService.java
  src/main/java/com/midnear/midnearshopping/service/review/ReviewsService.java
Labels: ✨ Feature

#98 [Fix] FE요청: 상품 카테고리별 정보 조회 오류 수정
  src/main/resources/mapper/ProductsMapper.xml
Labels: 🐞 BugFix

#99 [Fix] 상품 삭제, 상품 검색 수정
  src/main/java/com/midnear/midnearshopping/mapper/products/ProductColorsMapper.java
  src/main/java/com/midnear/midnearshopping/service/ProductManagementService.java
  src/main/resources/mapper/ProductColorsMapper.xml
  src/main/resources/mapper/ProductsMapper.xml
Labels: 🐞 BugFix

#100 [Fix] 리뷰 권한 체크 수정, 페이지 사이즈 및 장바구니 회원가입시 생기도록 수정
  src/main/java/com/midnear/midnearshopping/service/UsersService.java
  src/main/java/com/midnear/midnearshopping/service/inquirie/UserInquiryService.java
  src/main/java/com/midnear/midnearshopping/service/review/ReviewsService.java
  src/main/resources/mapper/CartMapper.xml
  src/main/resources/mapper/UsersMapper.xml
Labels: 🐞 BugFix

#101 [Fix] 장바구니 수정#73
  src/main/java/com/midnear/midnearshopping/controller/CartController.java
  src/main/resources/mapper/CartMapper.xml
Labels: 🐞 BugFix

#103 [Fix] 배송지 수정
  src/main/java/com/midnear/midnearshopping/controller/DeliveryController.java
  src/main/java/com/midnear/midnearshopping/mapper/delivery/DeliveryAddressMapper.java
  src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
  src/main/resources/mapper/DeliveryAddressMapper.xml
Labels: 🐞 BugFix

#104 [Fix] 전체 포인트 지급 수정
  src/main/java/com/midnear/midnearshopping/service/CouponPointService.java
Labels: 🐞 BugFix

#105 [Fix] String Dto로 감싸기
  src/main/java/com/midnear/midnearshopping/controller/StoreManagementController.java
  src/main/java/com/midnear/midnearshopping/domain/dto/policies_info/PolicyDto.java
Labels: 🐞 BugFix

#106 [Fix]배송지 수정 #73
  src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
Labels: 🐞 BugFix

#108 [Fix]배송지 수정
  src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
Labels: 🐞 BugFix

#109 [Fix]배송지 수정 진짜 최종 #73
  src/main/java/com/midnear/midnearshopping/service/delivery/DeliveryService.java
Labels: 🐞 BugFix

#110 [Feat] 배송비 띄우기
  src/main/java/com/midnear/midnearshopping/MidnearShoppingApplication.java
  src/main/java/com/midnear/midnearshopping/controller/productManage/ShippingManageController.java
  src/main/java/com/midnear/midnearshopping/mapper/productManagement/ShippingManagementMapper.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/ShippingManageService.java
  src/main/java/com/midnear/midnearshopping/service/productManagement/ShippingManageServiceImpl.java
  src/main/resources/mapper/DisruptiveCustomersMapper.xml
  src/main/resources/mapper/MagazinesMapper.xml
  src/main/resources/mapper/ShippingManagement.xml
Labels: ✨ Feature

#112 [Chore] 배송부분 엔드포인트 추가
  src/main/java/com/midnear/midnearshopping/config/SecurityConfig.java
  src/main/java/com/midnear/midnearshopping/controller/productManage/ShippingManageController.java
Labels: 📬 API

#114 [Fix] 관리자만 접근 허용
  src/main/java/com/midnear/midnearshopping/controller/CouponPointController.java
  src/main/java/com/midnear/midnearshopping/controller/NoticeManagementController.java
  src/main/java/com/midnear/midnearshopping/controller/ProductManagementController.java
  src/main/java/com/midnear/midnearshopping/controller/StoreManagementController.java
Labels: 🐞 BugFix

#115 [Fix]리뷰 페이징 오류 해결 #73
  src/main/java/com/midnear/midnearshopping/mapper/review/ReviewImagesMapper.java
  src/main/java/com/midnear/midnearshopping/service/review/ReviewsService.java
  src/main/resources/mapper/ReviewImagesMapper.xml
  src/main/resources/mapper/ReviewsMapper.xml
Labels: 🐞 BugFix
